CREATE TABLE CharacterStats(Id INTEGER PRIMARY KEY AUTOINCREMENT
, Strength INT NOT NULL
, Constitution INT NOT NULL
, Dexterity INT NOT NULL
, Intelligence INT NOT NULL
, Wisdom INT NOT NULL
, Charisma INT NOT NULL
, HpMax INT NOT NULL
, MpMax INT NOT NULL)